<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Test cases for Authentication</description>
   <name>Authentication</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-08-29T19:57:52</lastRun>
   <mailRecipient>jether.arcillas@dqr-group.com;arcillas.noraliza@dqr-group.com;</mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>961f681a-fab0-4164-9a31-81e91782c44e</testSuiteGuid>
   <testCaseLink>
      <guid>c2759a18-a34a-41b3-9152-045d38e3a175</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01 Authentication/Auth1</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2a102c6-fd5f-46cb-8cd1-ab7ad64ca226</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ac7bdae-4b57-47f4-9b8d-a868ee2f531c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1aff543e-b027-414f-bdbd-c891ab0bc3f3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01 Authentication/Auth2</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>550e2c86-56f5-43a9-b58d-d051c86ab84e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>498e70ee-b9b6-46ff-b39f-ed8bd47d03b2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01 Authentication/Auth3</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fac3f15f-c652-44c1-adcb-e19923e6d117</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4daa8520-76a0-490b-b943-79d7fa7c3eb7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b5e21d64-d9fd-449e-8f68-65456ff78293</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01 Authentication/Auth4</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c28be5c-bdd2-40f4-af1c-076d47b30448</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca5b3803-3c93-4227-992b-097516915dbe</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>53ead67a-3b03-4259-b175-8f65b9743952</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01 Authentication/Auth5</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a19f97b8-3ea5-4bfc-958e-0148652caa88</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99b0e1c8-19d8-4006-a864-7228f4513199</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
