<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Test suite for DQRXD-140</description>
   <name>Jira Ticket DQRXD-140</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-09-12T19:45:31</lastRun>
   <mailRecipient>jether.arcillas@dqr-group.com;arcillas.noraliza@dqr-group.com;</mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>f067d433-6fb3-416b-9b07-e5a9cd8f5fc5</testSuiteGuid>
   <testCaseLink>
      <guid>62b5381b-326e-44f2-a0fb-3274792c0164</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Jira Ticket/DQRXD-144</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>21e65660-7b88-47d3-907f-73c130e9a11e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Jira Ticket/DQRXD-145</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>3e7275bc-0009-4cfd-bb16-4728f7f61ded</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Jira Ticket/DQRXD-146</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6a49963-36a5-4765-9158-2c4b0681b217</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>31d600c8-9ef9-4007-9b5e-bed1f29a24b9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Jira Ticket/DQRXD-147</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>258ab1cd-64fe-4d2d-8d9a-d9c200bb27f4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28512bc3-2e87-4a22-99cd-026c4f9cd84d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8648f6d5-3d82-4ae3-ae95-03799da83c86</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9eebae35-bf65-4294-9a71-edf942b7a749</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4774e392-b472-42e5-897f-28fd8ff3b91b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1351a86b-d390-4ebb-9030-4800244482dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4121ae5-d68f-4aa4-9c07-c5ccb035af1b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7adc56d-52d8-48a9-a172-b226e010804b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c0c8b7b-9f0a-4161-8b69-7552d92d2104</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8da4ebb8-2eb0-4cb8-8e47-685b787c2cd1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Jira Ticket/DQRXD-148</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>eaa48b58-3acb-493f-9bf8-bae86c8c8323</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Jira Ticket/DQRXD-153 SC1</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57a80aef-db26-4c37-b69d-3ee8e82f2482</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc7534d6-6729-42d6-849a-208094306e8b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c728832-6cb8-4fe4-9058-75af91e711fd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>52e76bf8-775b-4b8c-9939-6098bbd837db</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Jira Ticket/DQRXD-153 SC2</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71531da2-0ff6-4c0d-9427-792ebda181dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3fa14771-95e1-471b-ae08-bb1474c16167</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cb5ce49a-92ab-4ca7-a988-cb2a8e866aaa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dee8531b-390a-42a8-877c-c0c3c2f288b6</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
