<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Login</name>
   <tag></tag>
   <elementGuidId>8a66de76-44b6-47e7-8c0c-f0c127850d21</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>login.html</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-btn signin hide-loggedin</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ap-translate</name>
      <type>Main</type>
      <value>HOME_DIRECT.LOGIN</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;domloaded&quot;]/body[@class=&quot;loggedout&quot;]/header[@class=&quot;header&quot;]/div[@class=&quot;main-container&quot;]/div[@class=&quot;header-inner&quot;]/div[@class=&quot;row w-100&quot;]/div[@class=&quot;col-8&quot;]/div[@class=&quot;wrap&quot;]/div[@class=&quot;login&quot;]/a[@class=&quot;login-btn signin hide-loggedin&quot;]</value>
   </webElementProperties>
</WebElementEntity>
