<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AddressField</name>
   <tag></tag>
   <elementGuidId>ee3db6e9-43ba-44dc-8fe9-29a1c2cca4d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;trade-deposit-dialog&quot;]/div/div[2]/div/div/div[2]/div/div/div[2]/select</value>
   </webElementProperties>
</WebElementEntity>
