<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Cancelbutton</name>
   <tag></tag>
   <elementGuidId>72aa3c7c-d73f-4738-90a4-c2921cbef199</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='trade-deposit-dialog']/div/div[2]/div/div/div/div[2]/div/div[2]/div[4]/div/button[1]</value>
   </webElementProperties>
</WebElementEntity>
