<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AmountField</name>
   <tag></tag>
   <elementGuidId>1495336c-d473-4297-85f3-55d0acc91d5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;trade-deposit-dialog&quot;]/div/div[2]/div/div/div/div[2]/div/div[2]/div[1]/div/div/input</value>
   </webElementProperties>
</WebElementEntity>
