<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ExternalAddress</name>
   <tag></tag>
   <elementGuidId>22085b6a-af43-4745-946f-e67a291657bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;trade-deposit-dialog&quot;]/div/div[2]/div/div/div/div[2]/div/div[2]/div[3]/div/input</value>
   </webElementProperties>
</WebElementEntity>
