<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PricePerBox</name>
   <tag></tag>
   <elementGuidId>34b677e7-5879-45e2-8cd6-3956e8d68d19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;trigger-content-1&quot;]/div/div/div/div/div/div/div[2]/div[2]/div/input</value>
   </webElementProperties>
</WebElementEntity>
